"""Minimal CogMem configuration for core schema modules."""

DEFAULT_EMBEDDING_DIMENSION = 384
EMBEDDING_DIMENSION = DEFAULT_EMBEDDING_DIMENSION

DEFAULT_DATABASE_SCHEMA = "public"
DATABASE_SCHEMA = DEFAULT_DATABASE_SCHEMA

DEFAULT_DB_POOL_MIN_SIZE = 2
DB_POOL_MIN_SIZE = DEFAULT_DB_POOL_MIN_SIZE

DEFAULT_DB_POOL_MAX_SIZE = 10
DB_POOL_MAX_SIZE = DEFAULT_DB_POOL_MAX_SIZE
